### ISSUE TITLE
Mobile store deployment: android and IOS (cost)

### ISSUE THREAD

**Issue by Butoxx69** [CPNV-ES/Joutes-Ionic#22]
65e2e5f4da0e793e9bce3fc75f51fffe1119a81d

**Comment by KevinJordil** [comment]
Android : https://support.google.com/googleplay/android-developer/answer/7159011?hl=fr
Inscription : 25$

**Comment by KevinJordil** [comment]
Apple : https://code.tutsplus.com/tutorials/how-to-submit-an-ios-app-to-the-app-store--mobile-16812
Inscription : 99$/year
